### ISSUE TITLE
How to build this app?

### ISSUE THREAD

**Issue by satishkumar** [sujit25/Human-hair-detection#1]
Thanks for this app.
Can you provide the instructions to build this app in netbeans?

I get the following error when trying to build it:
<<root>>/Human-hair-detection/nbproject/jfx-impl.xml:1212: Warning: **Could not find resource file **"<<root>>/Human-hair-detection/${libs.OpenCV.classpath}"** to copy.**
BUILD FAILED (total time: 0 seconds)

Alternatively, on trying to run the bundled HairDetection.jar file in dist/ folder, I get the error:
Caused by: java.lang.UnsatisfiedLinkError: no opencv_java310 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at hairdetection.OpenCVoperation.<init>(OpenCVoperation.java:79)
	at hairdetection.FXMLDocumentController.handleGenerateAction(FXMLDocumentController.java:76)

How to resolve these errors?

**Comment by mehulnahar** [comment]
Can you provide the instructions to build this app in Android studio?

**Comment by sujit25** [comment]
@satishkumar : _**Sorry**_ for delayed reply. For solving "**Caused by: java.lang.UnsatisfiedLinkError: no opencv_java310 in java.library.path**" you need to compile OpenCV natively from source. 
For compiling OpenCV 3.1.0 without Nvidia gpu follow steps given in [compile OpenCV from source to build jar](http://opencv-java-tutorials.readthedocs.io/en/latest/01-installing-opencv-for-java.html)

**For compiling OpenCV 3.1.0 with Nvidia gpu with Cuda8 :**
1.clone OpenCV 3.1.0 from daveselinger's repo - git@github.com:daveselinger/opencv.git  maintained by [daveselinger](https://github.com/daveselinger)
2. Follow remaining steps for OpenCV compilation from source as given in [compile OpenCV from source to build jar](http://opencv-java-tutorials.readthedocs.io/en/latest/01-installing-opencv-for-java.html)

**Once compilation is completed successfully:**
1. Add reference to opencv-310.jar available from newly generated binaries.
2. Go to **Hair Detection Netbeans Project > Properties > Run > VM Options** : add  -Djava.library.path=/path/to/lib/containing/opencv_libraries
for e.g. on my machine: -Djava.library.path="/home/sujit25/softwares/opencv-3.1.0-with-cuda8/release/lib" 

**Note:** I have not tested application with any OpenCV version above 3.1.0.

**Comment by sujit25** [comment]
@mehulnahar: This application is a GUI based standalone application built with Netbeans. You can refer to [getting started with opencv on android](https://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/O4A_SDK.html).

**Comment by biocrypto730** [comment]
your instructions did not solve the error. you copied the error wrong from the original issue. The error that i am getting is Could not find resource file "<>/Human-hair-detection/${libs.OpenCV.classpath}" to copy.

**Comment by biocrypto730** [comment]
* make sure you are on netbeans 8.2, not 8.1
* When clicking "Resolve problems" to figure out the OpenCV library, create a new library by selecting  "Add new library" in the bottom left. if you just add the opencv jar to an existing library it won't work 
* if you don't have an opencv jar follow instructions for compiling from source in readme

**Comment by biocrypto730** [comment]
Also had to disable DT to ignore java development toolkit error, as described here:

http://hongouru.blogspot.com/2015/09/solved-error-building-new-project-using.html

**Comment by biocrypto730** [comment]
nevermind, the library doesn't work at detecting hair

**Comment by sujit25** [comment]
@projectoblio : Please free to submit a pull request for making it work if you are interested. As you can see from screenshot of images posted, it did worked very well.
