### ISSUE TITLE
For Android App

### ISSUE THREAD

**Issue by mehulnahar** [sujit25/Human-hair-detection#2]
Can you provide the instructions to build this app in Android studio?

**Comment by sujit25** [comment]
@mehulnahar: This application is a GUI based standalone application built with Netbeans. You can refer to [getting started with opencv on android](https://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/O4A_SDK.html). You can use code given in OpenCVoperation.java with some modifications, since it contains core operations performed on input image. All other files contains code related to JavaFX application.
